sjobs:
  - { git_repo_url: https://github.com/Srikaanth62/roboshop_terraform.git, job_name: roboshop_terraform }
  - { git_repo_url: https://github.com/Srikaanth62/roboshop-ansible.git, job_name: roboshop-ansible }
  - { git_repo_url: https://github.com/Srikaanth62/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store }

mjobs:
  - { git_repo_url: https://github.com/Srikaanth62/cart.git, job_name: cart }
  - { git_repo_url: https://github.com/Srikaanth62/catalogue.git, job_name: catalogue }
  - { git_repo_url: https://github.com/Srikaanth62/user.git, job_name: user }
  - { git_repo_url: https://github.com/Srikaanth62/shipping.git, job_name: shipping }
  - { git_repo_url: https://github.com/Srikaanth62/payment.git, job_name: payment }
  - { git_repo_url: https://github.com/Srikaanth62/dispatch.git, job_name: dispatch }
